In [1]:
import numpy as np

In [5]:
# 3. Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 4)
12
2


In [6]:
# 4. Write python code to access the first row of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]


arr= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr[0]

array([1, 2, 3, 4])

In [7]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]


arr= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr[2][3]

12

In [8]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr[:,1::2])

[[ 2  4]
 [ 6  8]
 [10 12]]


In [21]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

np.random.rand(3,3)

array([[0.69605265, 0.85709497, 0.25159818],
       [0.70779099, 0.70751556, 0.19937646],
       [0.86756338, 0.92826903, 0.41897149]])

In [22]:
# 9. Write code to increase the dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
np.expand_dims(arr,axis=0)


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [23]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
np.transpose(arr)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [41]:
# 11. Consider the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

mat1=np.matrix([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
mat2=np.matrix([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

# Perform the following operation using Python1

# 1.) Index whiLe multiplication

print('multiply')
print(np.multiply(mat1,mat2)) 
# The * operator between NumPy matrices does not perform element-wise multiplication; instead, it performs matrix multiplication

# 2.) Matix multiplication
# we cant because it does not follow (n,p)*(p,m)

# 3.) Add both the maticx
print('addition')
print(np.add(mat1,mat2)) 
# print(mat1+mat2)

# 4.) Subtact matix B from A
print('subtract')
print(np.subtract(mat2,mat1)) 
# print(mat2-mat1)

# 5.) Divide Matix B by A

print('divide')
print(np.divide(mat2,mat1)) 
# print(mat2-mat1)

multiply
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
addition
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
subtract
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
divide
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

arr= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr.byteswap()

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

In [46]:
# # 14. What does the np.reshape function do, and how is it used?

# used to reshape numpy array
arr= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
np.reshape(arr,(2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

15. What is broadcasting in Numpy? 

broadcasting is a mechanism that is 